/* AUTO-GENERATED by scripts/build-yza-pricing-artifacts.mjs — do not edit by hand.
   Internal B2B/stockist pricing. Loaded ONLY by b2b.html so channel pricing never ships on
   home/product/collection/search pages. All values in MAD centimes. */
(function () {
  var YZA = (window.YZA = window.YZA || {});
  YZA.b2bPricing = {
  "yza-scarf-top-jawhara-ss26": {
    "name": "YZA Scarf Top",
    "retail": 35000,
    "wholesale": 30300,
    "stockist_retail_ttc": 90900
  },
  "yza-bateau-top-jawhara-ss26": {
    "name": "YZA Bateau Top",
    "retail": 55000,
    "wholesale": 45450,
    "stockist_retail_ttc": 136350
  },
  "yza-button-up-shirt-jawhara-ss26": {
    "name": "YZA Button-Up Shirt",
    "retail": 89000,
    "wholesale": 73050,
    "stockist_retail_ttc": 219150
  },
  "yza-pareo-skirt-short-jawhara-ss26": {
    "name": "YZA Pareo Skirt - Short",
    "retail": 45000,
    "wholesale": 37050,
    "stockist_retail_ttc": 111150
  },
  "yza-pareo-skirt-midi-jawhara-ss26": {
    "name": "YZA Pareo Skirt - Midi",
    "retail": 50000,
    "wholesale": 42450,
    "stockist_retail_ttc": 127350
  },
  "yza-pareo-skirt-long-jawhara-ss26": {
    "name": "YZA Pareo Skirt - Long",
    "retail": 59000,
    "wholesale": 48900,
    "stockist_retail_ttc": 146700
  },
  "yza-pareo-skirt-x-long-jawhara-ss26": {
    "name": "YZA Pareo Skirt - X Long",
    "retail": 59000,
    "wholesale": 48900,
    "stockist_retail_ttc": 146700
  },
  "yza-palazzo-pants-jawhara-ss26": {
    "name": "YZA Palazzo Pants",
    "retail": 75000,
    "wholesale": 63000,
    "stockist_retail_ttc": 189000
  },
  "yza-wrap-pants-jawhara-ss26": {
    "name": "YZA Wrap Pants",
    "retail": 99000,
    "wholesale": 52000,
    "stockist_retail_ttc": null
  },
  "la-sculpture-xs-basket-bag-ss26": {
    "name": "La Sculpture XS",
    "retail": 80000,
    "wholesale": 66300,
    "stockist_retail_ttc": 198900
  },
  "la-sculpture-s-basket-bag-ss26": {
    "name": "La Sculpture S",
    "retail": 95000,
    "wholesale": 77400,
    "stockist_retail_ttc": 232200
  },
  "la-sculpture-m-basket-bag-ss26": {
    "name": "La Sculpture M",
    "retail": 100000,
    "wholesale": 83100,
    "stockist_retail_ttc": 249300
  },
  "la-nouvelle-vague-xs-basket-bag-ss26": {
    "name": "La Nouvelle Vague XS",
    "retail": 49000,
    "wholesale": 40875,
    "stockist_retail_ttc": 122625
  },
  "la-nouvelle-vague-s-basket-bag-ss26": {
    "name": "La Nouvelle Vague S",
    "retail": 60000,
    "wholesale": 50125,
    "stockist_retail_ttc": 150375
  },
  "la-nouvelle-vague-m-basket-bag-ss26": {
    "name": "La Nouvelle Vague M",
    "retail": 65000,
    "wholesale": 54875,
    "stockist_retail_ttc": 164625
  },
  "raffia-cherries-charm-ss26": {
    "name": "Raffia Cherries Charm",
    "retail": 10000,
    "wholesale": 8625,
    "stockist_retail_ttc": 25875
  },
  "raffia-grapes-charm-ss26": {
    "name": "Raffia Grapes Charm",
    "retail": 19000,
    "wholesale": 16125,
    "stockist_retail_ttc": 48375
  },
  "raffia-whole-lemon-charm-ss26": {
    "name": "Raffia Whole Lemon Charm",
    "retail": 23000,
    "wholesale": 19000,
    "stockist_retail_ttc": 57000
  },
  "raffia-whole-orange-charm-ss26": {
    "name": "Raffia Whole Orange Charm",
    "retail": 23000,
    "wholesale": 19000,
    "stockist_retail_ttc": 57000
  },
  "raffia-tomato-charm-ss26": {
    "name": "Raffia Tomato Charm",
    "retail": 23000,
    "wholesale": 19000,
    "stockist_retail_ttc": 57000
  },
  "raffia-lemon-slice-charm-ss26": {
    "name": "Raffia Lemon Slice Charm",
    "retail": 19000,
    "wholesale": 15875,
    "stockist_retail_ttc": 47625
  },
  "raffia-orange-slice-charm-ss26": {
    "name": "Raffia Orange Slice Charm",
    "retail": 19000,
    "wholesale": 15875,
    "stockist_retail_ttc": 47625
  },
  "raffia-kiwi-slice-charm-ss26": {
    "name": "Raffia Kiwi Slice Charm",
    "retail": 19000,
    "wholesale": 15875,
    "stockist_retail_ttc": 47625
  },
  "raffia-watermelon-slice-charm-ss26": {
    "name": "Raffia Watermelon Slice Charm",
    "retail": 19000,
    "wholesale": 15875,
    "stockist_retail_ttc": 47625
  },
  "raffia-avocado-half-charm-ss26": {
    "name": "Raffia Avocado Half Charm",
    "retail": 19000,
    "wholesale": 15875,
    "stockist_retail_ttc": 47625
  },
  "watermelon-raffia-earrings-ss26": {
    "name": "Watermelon Raffia Earrings",
    "retail": 45000,
    "wholesale": 35625,
    "stockist_retail_ttc": 106875
  },
  "kiwi-raffia-earrings-ss26": {
    "name": "Kiwi Raffia Earrings",
    "retail": 45000,
    "wholesale": 35625,
    "stockist_retail_ttc": 106875
  },
  "lemon-raffia-earrings-ss26": {
    "name": "Lemon Raffia Earrings",
    "retail": 45000,
    "wholesale": 38625,
    "stockist_retail_ttc": 115875
  },
  "orange-raffia-earrings-ss26": {
    "name": "Orange Raffia Earrings",
    "retail": 45000,
    "wholesale": 38625,
    "stockist_retail_ttc": 115875
  },
  "grapes-raffia-earrings-ss26": {
    "name": "Grapes Raffia Earrings",
    "retail": 45000,
    "wholesale": 36125,
    "stockist_retail_ttc": 108375
  },
  "cherries-raffia-earrings-ss26": {
    "name": "Cherries Raffia Earrings",
    "retail": 25000,
    "wholesale": 21125,
    "stockist_retail_ttc": 63375
  },
  "tomatoes-raffia-earrings-ss26": {
    "name": "Tomatoes Raffia Earrings",
    "retail": 50000,
    "wholesale": 41625,
    "stockist_retail_ttc": 124875
  },
  "lemon-slice-raffia-necklace-ss26": {
    "name": "Lemon Slice Raffia Necklace",
    "retail": 26000,
    "wholesale": 21625,
    "stockist_retail_ttc": 64875
  },
  "orange-slice-raffia-necklace-ss26": {
    "name": "Orange Slice Raffia Necklace",
    "retail": 26000,
    "wholesale": 21625,
    "stockist_retail_ttc": 64875
  },
  "watermelon-slice-raffia-necklace-ss26": {
    "name": "Watermelon Slice Raffia Necklace",
    "retail": 26000,
    "wholesale": 21625,
    "stockist_retail_ttc": 64875
  },
  "grapes-raffia-necklace-ss26": {
    "name": "Grapes Raffia Necklace",
    "retail": 26000,
    "wholesale": 21875,
    "stockist_retail_ttc": 65625
  },
  "cherries-raffia-necklace-ss26": {
    "name": "Cherries Raffia Necklace",
    "retail": 17000,
    "wholesale": 14375,
    "stockist_retail_ttc": 43125
  }
};
})();
